### ISSUE TITLE
Help does not work

### ISSUE THREAD

**Issue by DarqueWarrior** [pnp/generator-teams#127]
**Describe the bug**
When I call the following command I get an error
```
yo teams --help
```

**To Reproduce**
Type
```
yo teams --help
```

**Expected behavior**
I expect to see help on parameters and sub generators.

**Screenshots**
```
PS R:\temp\tab> yo teams --help
C:\Users\user\AppData\Roaming\npm\node_modules\generator-teams\node_modules\yeoman-generator\lib\actions\help.js:68
  name = name.replace(/^yeoman:/, '');
              ^

TypeError: Cannot read property 'replace' of undefined
    at t.GeneratorTeamsApp.help.usage (C:\Users\user\AppData\Roaming\npm\node_modules\generator-teams\node_modules\yeoman-generator\lib\actions\help.js:68:15)
    at t.GeneratorTeamsApp.help.help (C:\Users\user\AppData\Roaming\npm\node_modules\generator-teams\node_modules\yeoman-generator\lib\actions\help.js:23:36)
    at instantiateAndRun (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:740:38)
    at Environment.run (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:758:12)
    at C:\Users\user\AppData\Roaming\npm\node_modules\yo\lib\cli.js:167:11
    at Environment.resolver.lookup (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:98:12)
    at init (C:\Users\user\AppData\Roaming\npm\node_modules\yo\lib\cli.js:128:7)
    at pre (C:\Users\user\AppData\Roaming\npm\node_modules\yo\lib\cli.js:87:3)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\yo\lib\cli.js:216:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30
```

**Detailed information**
 - Generator version: 2.15.0
 - Yeoman version: 3.1.1
 - OS: Windows
 - Node version: v12.16.3
 - Npm version: v6.14.5

**Additional information**

**Comment by wictorwilen** [comment]
Thanks for reporting this. Clearly an oversight and missing feature. Will add to the backlog. Meanwhile, you have all the parameters and docs in the Readme file.
