### ISSUE TITLE
Gulp validate-manifest and manifest not woking my environment

### ISSUE THREAD

**Issue by Ntakuya** [pnp/generator-teams#212]
**Describe the bug**

validate-manifest and manifest not woking my environment.

not display validate-manifest and manifest-task. and not generate package/manifest.json and also generate tmp

**To Reproduce**
1. `npm run build`

```terminal
 $ npm run build
 [13:07:31] Using gulpfile ~projectDirectory/gulpfile.js
[13:07:31] Starting 'build'...
[13:07:31] Starting 'webpack'...
[13:07:31] Starting 'webpack:client'...
[13:07:31] Starting 'webpack:server'...
[13:07:38] Finished 'webpack:server' after 6.72 s
[13:07:40] Finished 'webpack:client' after 9.19 s
[13:07:40] Finished 'webpack' after 9.19 s
[13:07:40] Starting 'styles'...
[13:07:40] Finished 'styles' after 81 ms
[13:07:40] Starting 'static:copy'...
[13:07:40] Finished 'static:copy' after 21 ms
[13:07:40] Starting 'static:inject'...
[13:07:40] gulp-inject 1 file into index.html.
[13:07:40] gulp-inject 1 file into privacy.html.
[13:07:40] gulp-inject 1 file into tou.html.
[13:07:40] Finished 'static:inject' after 20 ms
[13:07:40] Finished 'build' after 9.31 s
```

```terminal
$ tree . -I node_modules -L 2
.
├── Dockerfile
├── README-firstMessageOutgoingWebhook.md
├── README.md
├── dist
│   ├── server.js
│   ├── server.js.map
│   └── web
├── gulpfile.js
├── package
├── package-lock.json
├── package.json
├── src
│   ├── client
│   ├── manifest
│   ├── public
│   └── server
└── webpack.config.js 
```

**Expected behavior**

generate `package/NAME.zip`

**Screenshots**
none

**Detailed information**
 - OS: [MacOS]
 - Node version: [v14.16.1]
 - Npm version: [6.14.12]

**Additional information**

my package.json is. build by yo.

```
{
    "name": "sample-temas-application",
    "version": "0.0.1",
    "description": "Generated by yoteams, https://aka.ms/yoteams",
    "scripts": {
        "gulp": "./node_modules/.bin/gulp",
        "start": "node dist/server.js",
        "build": "./node_modules/.bin/gulp build",
        "lint": "eslint ./src --ext .js,.jsx,.ts,.tsx",
        "debug": "./node_modules/.bin/gulp serve --debug"
    },
    "dependencies": {
        "@fluentui/react-northstar": "~0.52.0",
        "@microsoft/teams-js": "~1.9.0",
        "axios": "^0.21.1",
        "botbuilder": "4.11.1",
        "botbuilder-dialogs": "4.11.1",
        "compression": "1.7.4",
        "debug": "4.2.0",
        "dotenv": "8.2.0",
        "express": "4.16.4",
        "express-msteams-host": "1.7.0",
        "express-session": "1.15.6",
        "morgan": "1.9.1",
        "react": "^16.8.6",
        "react-dom": "^16.8.6"
    },
    "devDependencies": {
        "@types/debug": "4.1.5",
        "@types/express": "4.16.0",
        "@types/express-session": "1.15.10",
        "@types/morgan": "1.7.35",
        "@types/react": "16.8.10",
        "@types/react-dom": "16.8.3",
        "@typescript-eslint/eslint-plugin": "^4.14.0",
        "@typescript-eslint/parser": "^4.14.0",
        "browser-sync": "^2.26.5",
        "dotenv-webpack": "^3.0.0",
        "eslint": "^7.18.0",
        "eslint-config-standard": "^16.0.2",
        "eslint-plugin-import": "^2.22.1",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-promise": "^4.2.1",
        "eslint-plugin-react": "^7.22.0",
        "eslint-plugin-react-hooks": "^4.2.0",
        "eslint-webpack-plugin": "^2.5.0",
        "fancy-log": "^1.3.3",
        "file-loader": "6.1.1",
        "gulp": "^4.0.2",
        "ngrok": "^3.1.1",
        "ts-loader": "8.0.5",
        "typescript": "4.0.3",
        "typestyle": "2.0.1",
        "vinyl": "2.2.0",
        "webpack": "5.0.0",
        "webpack-node-externals": "^2.5.2",
        "yargs": "^16.0.3",
        "yoteams-build-core": "^1.1.0"
    },
    "browserslist": [
        "> 1%",
        "last 2 versions",
        "Firefox ESR"
    ],
    "msteams": {
        "teamsAppId": "e0518f94-7ab8-400b-b89b-034d6359735f"
    }
}

```

**Comment by Ntakuya** [comment]
edit `node_modules/yoteams-build-core/dist/manifest.json`

```
  const zipTask = (cb) => {
        console.log(cb) // undefined
        return getManifests("temp/*.json")
            .pipe(flatmap((stream, file) => {
                console.log("aaaaaaaa") // without  this console not generate zip file
                if (!file.contents) {
                    throw new Error("Invalid file");
                }
                const data = file.contents.toString("utf-8");
                const json = JSON.parse(data);
                const zipName = json.packageName + ".zip";
                log(`Creating package ${zipName}`);
                return gulp.src(getPackageFiles(file))
                    .pipe(gulp_rename_1.default((path) => {
                    // for some reason rename uses a different definition fo basename
                    if (path.basename + path.extname === file.basename) {
                        return Object.assign(Object.assign({}, path), { basename: "manifest" });
                    }
                    return path;
            }))
                .pipe(zip(zipName));
        }))
            .pipe(gulp.dest("package"));
    };
   // export the tasks
    gulp.task("validate-manifest", _1.dependencies(gulp, generateManifests(), validateSchemas())); //add ()
    gulp.task("manifest", _1.dependencies(gulp, "validate-manifest", zipTask())); //add ()
```

**Comment by wictorwilen** [comment]
Thanks for reporting this @Ntakuya  - what version of yo teams are you using? Also what's the output when running `gulp manifest` - which is the task to generate the manifest?

**Comment by wictorwilen** [comment]
@Ntakuya - any update on this?

**Comment by Ntakuya** [comment]
@wictorwilen 
I'm sorry for late response.
My project is created by yo.

and version is

```terminal
% yo --version
3.1.1

% npm run gulp manifest --version
6.14.12
```
generator-teams version is `generator-teams@3.0.3`

**Comment by wictorwilen** [comment]
Thanks @Ntakuya.

As I wrote above what happens when you run `gulp manifest`, that is the command for generating the manifest `gulp build` only builds the application.

**Comment by Ntakuya** [comment]
im sorry for investing ur time.

so, and i write scripits in my package.json like...

```package.json
"scripts": {
        "gulp": "./node_modules/.bin/gulp",
        "start": "node dist/server.js",
        "build": "./node_modules/.bin/gulp build",
        "lint": "eslint ./src --ext .js,.jsx,.ts,.tsx",
        "debug": "./node_modules/.bin/gulp serve --debug",
        "gulp:manifest": "./node_modules/.bin/gulp manifest"
    },
``` 

and then i run `npm run gulp:manifest` .

i get error `[11:24:24] AssertionError [ERR_ASSERTION]: Task never defined: [object Object]`

shouid i rewrite my gulpfile.js?

my gulp file is 

 ``` gulfile.js
 // Copyright (c) Wictor Wilén. All rights reserved. 
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

const gulp = require("gulp");
const package = require("./package.json");
const argv = require("yargs").argv;
const log = require("fancy-log");
const path = require("path");

const config = {};

// Set environment variables
const env = argv.env;
if (env === undefined) {
    require("dotenv").config();
} else {
    log(`Using custom .env: ${env}`);
    require("dotenv").config({ path: path.resolve(process.cwd(), env) });
}
process.env.VERSION = package.version;

const core = require("yoteams-build-core");

// Initialize core build
core.setup(gulp, config);

// Add your custom or override tasks below

 ```

`npm run gulp:manifest error` 

```script-errro
> hubbleforteams@0.0.1 gulp:manifest teams-mock
[11:24PROJECT_PATH/gulpfile.js
[11:24:24] Starting 'manifest'...
[11:24:24] 'manifest' errored after 3.14 ms
[11:24:24] AssertionError [ERR_ASSERTION]: Task never defined: [object Object]
    at getFunction (PROJECT_PATH/node_modules/undertaker/lib/helpers/normalizeArgs.js:21:9)
    at map (PROJECT_PATH/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (PROJECT_PATH/node_modules/undertaker/lib/helpers/normalizeArgs.js:30:10)
    at Gulp.series (PROJECT_PATH/node_modules/undertaker/lib/series.js:13:14)
    at PROJECT_PATH/node_modules/yoteams-build-core/dist/index.js:21:27
    at manifest (PROJECT_PATH/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (PROJECT_PATH/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temas@0.0.1 gulp:manifest: `gulp manifest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the temas@0.0.1 gulp:manifest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     MY_USER/.npm/_logs/2021-05-11T02_24_24_529Z-debug.log```
```

**Comment by wictorwilen** [comment]
Thanks for the update @Ntakuya, files look ok.

What version of `yoteams-build-core` are you using? And what's the output of `gulp --tasks`?

**Comment by Ntakuya** [comment]
Thank you for answering.

my `yoteams-build-core` version is `"yoteams-build-core": "^1.1.0"` in my package.json in my project-directory.
and

and run script 
```terminal
%  hubbleforteams@0.0.1 gulp PROJECT_PATH
> gulp "--tasks"

[13:14:58] Tasks for ~PROJECT_PATH/gulpfile.js
[13:14:58] ├── validate-manifest
[13:14:58] ├── manifest
[13:14:58] ├── webpack:client
[13:14:58] ├── webpack:server
[13:14:58] ├── webpack
[13:14:58] ├── static:inject
[13:14:58] ├── static:copy
[13:14:58] ├── nuke
[13:14:58] ├── styles
[13:14:58] ├── build
[13:14:58] ├── watch
[13:14:58] ├── nodemon
[13:14:58] ├── serve
[13:14:58] ├── start-ngrok
[13:14:58] └── ngrok-serve
[13:14:58] Creating package hubbleforteams.zip
[13:14:58] manifest.json is using manifest schema 1.8

```

**Comment by wictorwilen** [comment]
can we test and downgrade `yoteams-build-core` to version 1.0.0?

**Comment by Ntakuya** [comment]
i'll try it!!!

**Comment by wictorwilen** [comment]
@Ntakuya - any update on this?

**Comment by Ntakuya** [comment]
@wictorwilen 
update all modules in global and project(like gulp-cli , yo, tems-builder)
successfully run any packages `gulp manifest`!!!!

Thank you for helping my issue and so sorry for investing time...

**Comment by wictorwilen** [comment]
Thanks for getting back and glad you resolved it
