### ISSUE TITLE
Bug report: SSO error

### ISSUE THREAD

**Issue by littlemd234** [pnp/generator-teams#298]
### Description

Hello, I'm trying to get the teams tab SSO example running. After using the `yo teams` command, adjusting the app ID and URLs I start the app using `gulp ngrok-serve`. The problem I'm facing right now comes when I try to add the "template" app to a team through App Studio - I can't save the new tab because the save button is grayed out.  There is also the following message written in the save popup:

```
Hello undefined
An SSO error occurred TypeError: Cannot read properties of undefined (reading 'resource')
```

I can see some js console errors:

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at e.getExtensionDefinition (https://statics.teams.cdn.office.net/hashed/3.2-app.min-85204ca.js:1:4061902)
```

```
0.2-angular-jquery.min-eee9041.js:114 TypeError: Cannot read properties of undefined (reading 'resource')
    at t.getValidatedResources (https://statics.teams.cdn.office.net/hashed/3.2-app.min-85204ca.js:1:4559985)
```

Could somebody give me a hint where to look for the problem? The console errors are related to some MS javascript files, not directly to my app.

The code of my tab that I'm trying to add is following:

```
import * as React from "react";
import { Provider, Flex, Text, Button, Header } from "@fluentui/react-northstar";
import { useState, useEffect } from "react";
import { useTeams } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";
import jwtDecode from "jwt-decode";

/**
 * Implementation of the Meeting content page
 */
export const MeetingTab = () => {

    const [{ inTeams, theme, context }] = useTeams();
    const [entityId, setEntityId] = useState<string | undefined>();
    const [name, setName] = useState<string>();
    const [error, setError] = useState<string>();

    useEffect(() => {
        if (inTeams === true) {
            microsoftTeams.authentication.getAuthToken({
                successCallback: (token: string) => {
                    const decoded: { [key: string]: any; } = jwtDecode(token) as { [key: string]: any; };
                    setName(decoded!.name);
                    microsoftTeams.appInitialization.notifySuccess();
                },
                failureCallback: (message: string) => {
                    setError(message);
                    microsoftTeams.appInitialization.notifyFailure({
                        reason: microsoftTeams.appInitialization.FailedReason.AuthFailed,
                        message
                    });
                },
                resources: [process.env.TAB_APP_URI as string]
            });
        } else {
            setEntityId("Not in Microsoft Teams");
        }
    }, [inTeams]);

    useEffect(() => {
        if (context) {
            setEntityId(context.entityId);
        }
    }, [context]);

    /**
     * The render() method to create the UI of the tab
     */
    return (
        <Provider theme={theme}>
            <Flex fill={true} column styles={{
                padding: ".8rem 0 .8rem .5rem"
            }}>
                <Flex.Item>
                    <Header content="This is your tab" />
                </Flex.Item>
                <Flex.Item>
                    <div>
                        <div>
                            <Text content={`Hello ${name}`} />
                        </div>
                        {error && <div><Text content={`An SSO error occurred ${error}`} /></div>}

                        <div>
                            <Button onClick={() => alert("It worked!")}>A sample button</Button>
                        </div>
                    </div>
                </Flex.Item>
                <Flex.Item styles={{
                    padding: ".8rem 0 .8rem .5rem"
                }}>
                    <Text size="smaller" content="(C) Copyright sw" />
                </Flex.Item>
            </Flex>
        </Provider>
    );
};
```

Greetings
Martin

### Steps to reproduce

1. Create a MS Teams Tab app
2. Adjust App ID and URL with ngrok URL.
3. Side-load the app into MS Teams and add it to a team

### Expected results

The Save button when adding to a team should not be grayed out.

### Actual results

The Save button is grayed out and I can't add my tab to a team.

### Project you experience issues with

generator-teams

### generator version

3.5.0

### build tools version

1.6.0

### nodejs version

16.14.0

### npm version

8.3.1

### Operating system (environment)

Windows

**Comment by wictorwilen** [comment]
@mwdoerner thanks for reporting this. Looks like your `TAB_APP_URI` variable in the `.env` file is empty or non existing.

**Comment by littlemd234** [comment]
Hi, the variable was set. For some strange reason it started to work some hours after I posted this issue - I'm not sure if I changed something that caused my project to work or if I had to wait some time for an activation on MS side. Anyway, thanks for the reply!
