### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by coatsy** [pnp/generator-teams#40]
Any request to the generated bot seems to throw the following exception:

```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at C:\Users\coats\source\repos\yo-teams-test\dist\server.js:113:9
    at Layer.handle [as handle_request] (C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\index.js:275:10)
    at next (C:\Users\coats\source\repos\yo-teams-test\node_modules\express\lib\router\route.js:127:14)
    at C:\Users\coats\source\repos\yo-teams-test\node_modules\botbuilder\lib\bots\ChatConnector.js:481:21
```

Then the request seems to be served appropriately

**Comment by wictorwilen** [comment]
This is a known issue, fixed in upcoming refactored release. It does not affect functionality, just annoying logging.

**Comment by wictorwilen** [comment]
@coatsy - can you please test with the new preview

> npm install generator-teams@preview --global

**Comment by coatsy** [comment]
Fixed in latest preview
