### ISSUE TITLE
ReferenceError: global is not defined for 2.7-preview@1

### ISSUE THREAD

**Issue by cagdasdavulcu** [pnp/generator-teams#65]
**Describe the bug**
I'm implementing server component tests for generator-teams via. supertest npm package. I implemented a sample test (you can find it here):
https://github.com/cagdasdavulcu/cd-test-05/blob/master/src/app/__tests__/Server.spec.ts

if i run the tests, then i'm getting an exception **ReferenceError: global is not defined** from the package 'express-msteams-host'.

You can use my sample repository for reproducing the problem (just clone it and run the command 'npm run test'):
https://github.com/cagdasdavulcu/cd-test-05

**Screenshots**
![image](https://user-images.githubusercontent.com/1059729/56506413-bdd83c00-651e-11e9-9ed2-014f695d3715.png)

**ReferenceError: global is not defined**

       5 | import { MsTeamsApiRouter, MsTeamsPageRouter } from "express-msteams-host";
       6 | import * as debug from "debug";
    >  7 |
         | ^
       8 | // Initialize debug logging module
       9 | const log = debug("msteams");
      10 |

      at eval (eval at Object.<anonymous> (node_modules/botframework-connector/src/index.ts:1:2), <anonymous>:3:13)
      at Object.<anonymous> (node_modules/botframework-connector/src/index.ts:1:213)
      at Object.<anonymous> (node_modules/botbuilder/src/botFrameworkAdapter.ts:10:1)
      at Object.<anonymous> (node_modules/botbuilder/src/index.ts:9:1)
      at Object.<anonymous> (node_modules/express-msteams-host/lib/routers/MsTeamsApiRouter.js:43:20)
      at Object.<anonymous> (node_modules/express-msteams-host/lib/routers/index.js:5:26)
      at Object.<anonymous> (node_modules/express-msteams-host/lib/index.js:9:10)
      at Object.<anonymous> (src/app/server.ts:7:30)
      at Object.<anonymous> (src/app/__tests__/Server.spec.ts:4:16)

**Detailed information**
 - Generator version: [2.7.1-preview@1]
 - OS: [Windows]
 - Node version: [10.15.3]
 - Npm version: [6.9.0]

**Comment by wictorwilen** [comment]
You can get around that issue by adding `window.global = window;` to the `test-shim.js` file. But that leads to further issues down the road. As the project is compiled with two different tsconfig files; one for the server side components (`tsconfig.json`) and one for the client side components (`tsconfig-client.json`).

**Comment by cagdasdavulcu** [comment]
Thank you!
