### ISSUE TITLE
gulp manifest result in schema-validation error

### ISSUE THREAD

**Issue by bhishma** [pnp/generator-teams#67]
[15:07:06] 'schema-validation' errored after 21 s
[15:07:06] SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (D:\Source\Repos\cqwp\gulpfile.js:151:64)
    at self.callback (D:\Source\Repos\cqwp\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.onRequestError (D:\Source\Repos\cqwp\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)

**Comment by cagdasdavulcu** [comment]
Hello @bhishma ,
can you please give us more information, thereby we can reproduce it? Did you change the manifest file manually? Can you also inform us, which node & npm version are you using?

**Comment by wictorwilen** [comment]
@bhishma - as the schema validation downloads the JSON schema on each build this might happen if you either don't have access to internet or you have enterered an invalid schema URL. As @cagdasdavulcu says - please share the manifest file you have (`src/manifest/manifest.json`) and also which version of the generator you are using. From version *2.7.0* only schema `1.3` and `devPreview` are supported (and if you're using something else you should get another error). As a workaround if you don't have internet access is to use first `gulp generate-manifest` and the `gulp zip`.

**Comment by bhishma** [comment]
Thank you @wictorwilen  and @cagdasdavulcu . I was working behind corporate proxy. It must have blocked the the access. I am able to generate the manifest file with `gulp generate-manifest` and `gulp zip`

**Comment by wictorwilen** [comment]
Thanks. Let's see how we can improve this going forward and catch the error and skip validation.
