### ISSUE TITLE
Message extensions fails when the name starts with a number

### ISSUE THREAD

**Issue by wictorwilen** [pnp/generator-teams#70]
**Describe the bug**
When creating a messaging extension that has a name that starts with a number the generator fails with the following exception:

```Error: Unexpected scenario where a(n) OpenBraceToken was not found.
-- Details --
Path: C:/code/test/272a/src/app/272AMessageExtensionBot/272AMessageExtensionBot.ts
Text: "...ssor, CardFactory, TurnContext, MemoryStorage, ConversationState, ActivityTypes } from \"botbuilder\";\nimport 272AMessageExtension from \"../272AMessageExtension/272AMessageExtension\";\nimport { TeamsContext, TeamsActivityProcessor } from \"botbuilder-teams\";\r\n\r\n// Initialize debug logging module\r\nconst log = debug(\"msteams\");\r\n\r\n/**\r\n * Implementation for 2..."
Stack: Error: Unexpected scenario where a(n) OpenBraceToken was not found.
    at getTokenEnd (C:\code\github\generator-teams\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:87:23)
    at Function.getContainerBodyPos (C:\code\github\generator-teams\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:78:20)
    at getNodes (C:\code\github\generator-teams\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:98:48)
    at getNodes.next (<anonymous>)
    at Function.from (native)
    at Function.getOrParseChildren (C:\code\github\generator-teams\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:37:30)
    at Function.getCompilerForEachChildren (C:\code\github\generator-teams\node_modules\ts-morph\dist\compiler\ast\utils\ExtendedParser.js:26:79)
```

**To Reproduce**
1. Generate a new project
2. Choose a message extension
3. Give the name to the message extension something that starts with a number (for example `111 Test`
4. Now it will fail when writing files

**Expected behavior**
That it does not fail - likely renames the file/class so it does not start with a number, or checks that during the input process

**Screenshots**

**Detailed information**
 - Generator version: 2.7.1
 - OS: Windows
 - Node version: 8.15.0
 - Npm version: 6.9.0

**Comment by wictorwilen** [comment]
Fixed in 2.8.0 (cfe6bc363b5944a4d90719efa2dd5a2b04692c42)
