### ISSUE TITLE
Unable to debug app through VSCode

### ISSUE THREAD

**Issue by Alexp2019** [pnp/generator-teams#90]
Experiencing issues debugging and using breakpoints within VSCode.

I've ran gulp serve --debug
and then added the following snippet (from the readme) and swapped the port to match. 
```
{
    "type": "node",
    "request": "attach",
    "name": "Attach",
    "port": 9229,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/dist/**/*.js"
    ],
    "remoteRoot": "${workspaceRoot}/src/"
}
```

The debugger attaches successfully, but the breakpoints are greyed out with the following message:
"Breakpoint ignored because generated code not found (source map problem)?

I saw a similar issue posted here where the remoteRoot was removed, I tried that but still experience the same issue.

Thanks.

edit: Looks like I can set breakpoints on server.ts, but any of the tsx files show the 'breakpoint ignored because generated code not found' message:

![image](https://user-images.githubusercontent.com/38928645/69851784-45b0d080-12ce-11ea-9b9a-6b546d2ebe3a.png)

**Comment by wictorwilen** [comment]
the `.tsx` files are transpiled into client side JavaScript, so you can't use node.js debugging (`type=node`, `request=attach`) as your configuration. Change as follows (depending on your browser):

```
 {
            "type": "edge",
            "request": "attach",
            "name": "Client",
            "port": 9222,
            "sourceMaps": true,
            "trace": "verbose",
            "webRoot": "${workspaceFolder}\\dist\\web"
}

**Comment by Alexp2019** [comment]
Thanks for the response - I have tried adding the config but experiencing the below:

Debugger listening on ws://127.0.0.1:9229/ea9e23a0-b25b-4512-80ea-7967e954451f
Using:
```
        {
            "type": "chrome",
            "request": "attach",
            "name": "Client",
            "port": 9229,
            "sourceMaps": true,
            "trace": "verbose",
            "webRoot": "${workspaceFolder}\\dist\\web"
        }
```

```
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/attach","data":{"Versions.DebugAdapterCore":"6.8.4","Versions.DebugAdapter":"4.12.1","successful":"false","exceptionType":"firstChance","exceptionMessage":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","exceptionName":"Error","exceptionStack":"Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).\n    at Object.runtimeConnectionTimeout (errors.js:91:12)\n    at chromeConnection.js:110:49\n    at processTicksAndRejections (internal/process/task_queues.js:89:5)","exceptionId":"2010","timeTakenInMilliseconds":"9817.027601","requestType":"request"}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a valid target that matches: undefined. Available pages: [\"file://C:_Users_user_Documents_GitHub_tabname-prev_dist_server.js\"]).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Can't find a valid target that matches: undefined. Available pages: [\"file://C:_Users_user_Documents_GitHub_tabname-prev_dist_server.js\"]","_timeout":"10000"}}}}
```

edit: I can now attach the debugger, but I'm receiving the '"Breakpoint ignored because generated code not found (source map problem)' error.
logs:
```
{"error":{"code":-32601,"message":"'Runtime.run' wasn't found"},"id":6}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"client.js","path":"http://127.0.0.1:3007/scripts/client.js","sourceReference":1000}}}
From client: setBreakpoints({"source":{"name":"Tab.tsx","path":"c:\\Users\\user\\Documents\\GitHub\\tab-prod\\src\\app\\scripts\\tab\\tab.tsx"},"lines":[58,59,60,61,75,82],"breakpoints":[{"line":58},{"line":59},{"line":60},{"line":61},{"line":75},{"line":82}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"Versions.DebugAdapterCore":"6.8.6","Versions.DebugAdapter":"4.12.2","fileExt":".tsx"}}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":58,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000},{"verified":false,"line":59,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1001},{"verified":false,"line":60,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1002},{"verified":false,"line":61,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1003},{"verified":false,"line":75,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1004},{"verified":false,"line":82,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1005}]}}
```

I can see all interactions via the debug console, i.e. button press etc. but the breakpoints are just unverified.

**Comment by wictorwilen** [comment]
As you're trying to debug your client side code, inside Microsoft Teams, you're trying to debug something in an Iframe. This does unfortunately not work (see https://github.com/Microsoft/vscode-chrome-debug/issues/786).

What I do is that use the webpack info and devtools in Chrome/Chredge and debug within the browser. Very easy to set up. Just navigate to the iframe of your app, and locate the webpack bundle inside the source code (will be visible as soon as the .map file is loaded)

**Comment by Alexp2019** [comment]
> As you're trying to debug your client side code, inside Microsoft Teams, you're trying to debug something in an Iframe. This does unfortunately not work (see [microsoft/vscode-chrome-debug#786](https://github.com/microsoft/vscode-chrome-debug/issues/786)).
> 
> What I do is that use the webpack info and devtools in Chrome/Chredge and debug within the browser. Very easy to set up. Just navigate to the iframe of your app, and locate the webpack bundle inside the source code (will be visible as soon as the .map file is loaded)

Thanks for the reply, 
I'm using chrome and just browsing to the site directly and the Chrome Debugger extension for vscode, do you have any screenshots of how you're doing the debugging, and are you able to set breakpoints? 
Thanks :)

**Comment by wictorwilen** [comment]
Closing this due to inactivity
